ezpublishvol:
  image: debian:jessie
  volumes:
   - ./volumes/ezpublish:/var/www
  # Remove .keep file so composer is able to install in the directory afterwards. UID=10000 and GUID=10000 is ez user in ezphp image
  command: bash -c "rm /var/www/.keep; chown 10000:10000 /var/www"

composercachevol:
  image: debian:jessie
  volumes:
   - ./volumes/composercache:/var/.composer/cache
  command: chown 10000:10000 /var/.composer/cache

ezphp:
  image: ezsystems/ezphp
  user: ez
  volumes_from:
   - ezpublishvol
   - composercachevol
  volumes:
   - ./files/auth.json:/var/.composer/auth.json
   - ./files/kickstart_template.ini:/kickstart_template.ini
   # Override command, we don't want to start php-fpm just yet, just want to run composer command
   # That is done in docker-compose_ezpinstall.sh since it needs env variables (todo: fix when on Compose 1.4)
  command: php -v
