# Default container setup
# Simple single server setup
# Uses Debian Jessie and official images when possible


dbvol:
  image: debian:jessie
  volumes:
   - volumes/mysql:/var/lib/mysql

ezpublishvol:
  image: debian:jessie
  volumes:
   - volumes/ezpublish:/var/www

db1:
  image: mariadb:latest
  volumes_from:
   - dbvol
  environment:
   - MYSQL_ROOT_PASSWORD=mysecretrootpassword
   - MYSQL_USER=admin
   - MYSQL_PASSWORD
   - MYSQL_DATABASE=ezp

phpfpm1:
  # docker compose does not allow to specify container name, this is what it generates, might be fixed in 1.3
  image: ezpublishdocker_ezpphp:latest
  links:
   - db1:db
  volumes_from:
   - ezpublishvol
  environment:
   - EZ_KICKSTART
   - EZ_KICKSTART_FROM_TEMPLATE
   - EZ_ENVIRONMENT
   - MYSQL_PASSWORD

web1:
  build: dockerfiles/nginx
  links:
   - phpfpm1:php_fpm
  volumes_from:
   - ezpublishvol
  ports:
   - "8080:80"
  environment:
   - EZ_ENVIRONMENT
   - VARNISH_ENABLED
   - DOCKER0NET

#sahi:
#  build: dockerfiles/debian/sahi
#  links:
#   - nginx:web
#  ports:
#   - "9999:9999"
#   - "5900:5900"

#behatphpcli:
#  build: dockerfiles/debian/php-cli
#  links:
#   - db1:db
#   - nginx:web
#   - sahi:sahi
#  volumes_from:
#   - ezpublishvol

#varnish:
#  build: dockerfiles/debian/varnish
#  links:
#   - phpfpm:php_fpm
#   - nginx:nginx
#  volumes_from:
#   - ezpublishvol
#  ports:
#   - "8081:80"
#  environment:
#   - VARNISH_ENABLED
