# Default container setup
# Simple single server setup
# Uses Debian Jessie and official images when possible


dbvol:
  image: debian:jessie
  volumes:
   - ./volumes/mysql:/var/lib/mysql

ezpublishvol:
  image: debian:jessie
  volumes:
   - ./volumes/ezpublish:/var/www

db1:
  image: mariadb:latest
  volumes_from:
   - dbvol
  volumes:
   - ./resources/database_character_set.sh:/docker-entrypoint-initdb.d/database_character_set.sh
  environment:
   - MYSQL_ROOT_PASSWORD=mysecretrootpassword
   - MYSQL_USER=ezp
   - MYSQL_PASSWORD
   - MYSQL_DATABASE=ezp
   - TERM=dumb

solr1:
  image: makuk66/docker-solr:4.10.4
  volumes_from:
    - ezpublishvol
  command: /bin/bash -c "cp -R /var/www/vendor/ezsystems/ezplatform-solr-search-engine/lib/eZ/Publish/Core/Search/Solr/Resources/* /opt/solr/example/solr/collection1/conf/
    && /opt/solr/bin/solr start -f"


phpfpm1:
  # docker compose does not allow to specify container name, this is what it generates, might be fixed in 1.3
  image: ezsystems/ezphp
  links:
   - db1:db
   - solr1:solr
  volumes_from:
   - ezpublishvol
  environment:
   - EZ_KICKSTART
   - EZ_KICKSTART_FROM_TEMPLATE
   - EZ_ENVIRONMENT
   - MYSQL_PASSWORD

web1:
  image: ezsystems/web
  links:
   - phpfpm1:php_fpm
  volumes_from:
   - ezpublishvol
  ports:
   - "8080:80"
  environment:
   - EZ_ENVIRONMENT
   - VARNISH_ENABLED
   - DOCKER0NET

#
#varnish:
#  build: dockerfiles/internal/varnish
#  links:
#   - phpfpm:php_fpm
#   - nginx:nginx
#  volumes_from:
#   - ezpublishvol
#  ports:
#   - "8081:80"
#  environment:
#   - VARNISH_ENABLED
